<x-pages pageTitle="AI Development" pageTitleAll="AI Development" title="AI Development"
    imgesUrlOne="{{ asset('/images/Dev/AI/HuggingFace.png') }}"
    imgesUrlTwo="{{ asset('/images/Dev/AI/Cohere.png') }}"
    imgesUrlThree="{{ asset('/images/Dev/AI/Kaggle.png') }}"
    imgesUrlFour="{{ asset('/images/Dev/AI/OpenAIPlatform.webp') }}"
    imgesUrlFive="{{ asset('/images/Dev/AI/GoogleAIStudio.png') }}"
    imgesUrlSix="{{ asset('/images/Dev/AI/VertexAI.png') }}"
    imgesUrlSeven="{{ asset('/images/Dev/AI/AnthropicConsole.jpg') }}"
    imgesUrlEight="{{ asset('/images/Dev/AI/SiliconFlow.png') }}"
    imgesUrlNine="{{ asset('/images/Dev/AI/Replicate.jpg') }}"
    imgesUrlTen="{{ asset('/images/Dev/AI/GoogleColab.png') }}"
    imgesUrlEleven="{{ asset('/images/Dev/AI/PaperspaceGradient.jpg') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/AI/Cursor.avif') }}"
    imgesUrlThirteen="{{ asset('/images/Dev/AI/BoltNew.png') }}"
    imgesUrlFourteen="{{ asset('/images/Dev/AI/Pinecone.png') }}"
    imgesUrlFifteen="{{ asset('/images/Dev/AI/LangSmith.jpg') }}"
    imgesUrlSixteen="{{ asset('/images/Dev/AI/GroqCloud.png') }}"
    imgesUrlSeventeen="{{ asset('/images/Dev/FrontEnd/RoadmapSh.png') }}"
    imgesUrlEighteen="{{ asset('/images/Dev/AI/TogetherAI.png') }}"
    imgesUrlNineteen="{{ asset('/images/Dev/AI/MistralAI.png') }}"
    imgesUrlTwenty="{{ asset('/images/Dev/AI/Ollama.png') }}"
    imgesUrlTwentyOne="{{ asset('/images/Dev/AI/LMStudio.jpg') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/FrontEnd/GitHub.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/Dev/AI/ModelScope.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/Dev/AI/lamaIndex.jpg') }}"
    imgesUrlTwentyFive="{{ asset('/images/Dev/FrontEnd/freeCodeCamp.png') }}"
    imgesUrlTwentySix="{{ asset('/images/Dev/AI/Haystack.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/Dev/AI/PyTorch.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/Dev/AI/TensorFlow.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/Dev/AI/Keras.png') }}"
    imgesUrlThirty="{{ asset('/images/Dev/AI/PaperswithCode.webp') }}"
    imgesUrlThirtyone="{{ asset('/images/Dev/AI/UCIMachineLearningRepository.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/Dev/AI/arXivAIPapers.png') }}"
    imgesUrlThirtythree="{{ asset('/images/Dev/AI/TowardsDataScience.jpg') }}"
    imgesUrlThirtyfour="{{ asset('/images/Dev/AI/AnalyticsVidhya.png') }}"
    imgesUrlThirtyfive="{{ asset('/images/Dev/AI/claude.png') }}"
    imgesUrlThirtysix="{{ asset('/images/Dev/AI/CrewAI.png') }}"
    imgesUrlThirtyseven="{{ asset('/images/Dev/AI/copilot.webp') }}"
    routeNameOne="HuggingFace" routeNameTwo="Cohere" routeNameThree="Kaggle" routeNameFour="OpenAIPlatform" routeNameFive="GoogleAIStudio" routeNameSix="VertexAI" routeNameSeven="AnthropicConsole" routeNameEight="SiliconFlow" routeNameNine="Replicate" routeNameTen="GoogleColab" routeNameEleven="PaperspaceGradient" routeNameTowlve="Cursor"
    routeNameThirteen="BoltNew" routeNameFourteen="Pinecone" routeNameFifteen="LangSmith" routeNameSixteen="GroqCloud" routeNameSeventeen="RoadmapSh" routeNameEighteen="TogetherAI" routeNameNineteen="MistralAI" routeNametwenty="Ollama" routeNametwentyone="LMStudio" routeNametwentytwo="GitHub" routeNametwentythree="ModelScope"
routeNametwentyfour="LlamaIndex" routeNametwentyfive="freeCodeCamp" routeNametwentysix="Haystack" routeNametwentyseven="PyTorch" routeNametwentyeight="TensorFlow" routeNametwentynine="Keras" routeNamethirty="PaperswithCode" routeNamethirtyone="UCIMachineLearningRepository" routeNamethirtytwo="arXivAIPapers" routeNamethirtythree="TowardsDataScience"
    routeNamethirtyfour="AnalyticsVidhya" routeNamethirtyfive="claude" routeNamethirtysix="CrewAI" routeNamethirtyseven="copilot">
    <x-slot:PageTitle>
        AI Development - Lap Tools Web
        </x-slot>
</x-pages>
