<x-pages pageTitle="UI/UX" pageTitleAll="UI/UX " title="UI/UX "
    imgesUrlOne="{{ asset('/images/Design/Behance.jpg') }}"
    imgesUrlTwo="{{ asset('/images/Dev/UI/UXPin.png') }}"
    imgesUrlThree="{{ asset('/images/Design/dribbble.png') }}"
    imgesUrlFour="{{ asset('/images/Design/pinterest.gif') }}"
    imgesUrlFive="{{ asset('/images/Design/Mobbin.jpg') }}"
    imgesUrlSix="{{ asset('/images/Design/Flaticon.png') }}"
    imgesUrlSeven="{{ asset('/images/Dev/Frontend/Netlify.png') }}"
    imgesUrlEight="{{ asset('/images/Design/unDraw.png') }}"
    imgesUrlNine="{{ asset('/images/Dev/UI/Storyset.png') }}"
    imgesUrlTen="{{ asset('/images/Dev/Mobile/FontAwesome.png') }}"
    imgesUrlEleven="{{ asset('/images/Dev/Mobile/lottiefiles.jpg.jpg') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/UI/Iconify.png') }}"
    imgesUrlThirteen="{{ asset('/images/Dev/UI/FigmaCommunity.png') }}"
    imgesUrlFourteen="{{ asset('/images/Dev/UI/LandBook.jpg') }}"
    imgesUrlFifteen="{{ asset('/images/Dev/UI/PageFlows.jpg') }}"
    imgesUrlSixteen="{{ asset('/images/Dev/UI/SaaSframe.webp') }}"
    imgesUrlSeventeen="{{ asset('/images/Dev/Mobile/RoadmapSh.png') }}"
    imgesUrlEighteen="{{ asset('/images/Dev/UI/RealtimeColors.png') }}"
    imgesUrlNineteen="{{ asset('/images/Design/Coolors.png') }}"
    imgesUrlTwenty="{{ asset('/images/Design/khroma.jpg') }}"
    imgesUrlTwentyOne="{{ asset('/images/Dev/Mobile/Haikei.webp') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/UI/Typewolf.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/Dev/Frontend/GoogleFonts.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/Dev/UI/FontShare.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/Dev/Mobile/freeCodeCamp.png') }}"
    imgesUrlTwentySix="{{ asset('/images/Dev/UI/Whimsical.jpg') }}"
    imgesUrlTwentySeven="{{ asset('/images/Dev/UI/Balsamiq.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/Design/Awwwards.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/Dev/UI/LawsofUX.png') }}"
    imgesUrlThirty="{{ asset('/images/Dev/UI/NielsenNormanGroup).png') }}"
    imgesUrlThirtyone="{{ asset('/images/Dev/UI/UXArchive.ico') }}"
    imgesUrlThirtytwo="{{ asset('/images/Dev/UI/GrowthDesign.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/Dev/UI/Sketch.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/Dev/UI/AxureRP.png') }}"
    imgesUrlThirtyfive="{{ asset('/images/Dev/UI/AdobeXD.webp') }}"
    imgesUrlThirtysix="{{ asset('/images/Dev/UI/UI8.jpg') }}"
    imgesUrlThirtyseven="{{ asset('/images/Dev/Frontend/CollectUI.jpg') }}"
    routeNameOne="Behance" routeNameTwo="UXPin" routeNameThree="Pinterest" routeNameFour="Pinterest" routeNameFive="Mobbin" routeNameSix="Flaticon" routeNameSeven="Netlify" routeNameEight="unDraw" routeNameNine="Storyset" routeNameTen="FontAwesome" routeNameEleven="Lottiefiles" routeNameTowlve="Iconify"
    routeNameThirteen="FigmaCommunity" routeNameFourteen="LandBook" routeNameFifteen="PageFlows" routeNameSixteen="SaaSframe" routeNameSeventeen="RoadmapSh" routeNameEighteen="RealtimeColors" routeNameNineteen="Coolors" routeNametwenty="Khroma" routeNametwentyone="Haikei" routeNametwentytwo="Typewolf" routeNametwentythree="GoogleFonts"
    routeNametwentyfour="FontShare" routeNametwentyfive="freeCodeCamp" routeNametwentysix="Whimsical" routeNametwentyseven="Balsamiq" routeNametwentyeight="Awwwards" routeNametwentynine="LawsofUX" routeNamethirty="NielsenNormanGroup" routeNamethirtyone="UXArchive" routeNamethirtytwo="GrowthDesign" routeNamethirtythree="Sketch"
    routeNamethirtyfour="AxureRP" routeNamethirtyfive="AdobeXD" routeNamethirtysix="UI8" routeNamethirtyseven="CollectUI">
</x-pages>
