<x-Pages pageTitle="Editing" pageTitleAll="Editing " title="Editing"
    imgesUrlOne="{{ asset('/images/Editing/Clipchamp.png') }}"
    imgesUrlTwo="{{ asset('/images/Editing/Photopea.png') }}"
    imgesUrlThree="{{ asset('/images/Editing/Kapwing.png') }}"
    imgesUrlFour="{{ asset('/images/Editing/AdobePremierePro.png') }}"
    imgesUrlFive="{{ asset('/images/Editing/DaVinciResolve.jpg') }}"
    imgesUrlSix="{{ asset('/images/Editing/CapCut.png') }}"
    imgesUrlSeven="{{ asset('/images/Design/Canva.jpg') }}"
    imgesUrlEight="{{ asset('/images/Editing/VeedIo.png') }}"
    imgesUrlNine="{{ asset('/images/Editing/InVideo.webp') }}"
    imgesUrlTen="{{ asset('/images/Editing/Animoto.png') }}"
    imgesUrlEleven="{{ asset('/images/Editing/Mixkit.png') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/Games/Freesound.png') }}"
    imgesUrlThirteen="{{ asset('/images/Editing/EpidemicSound.png') }}"
    imgesUrlFourteen="{{ asset('/images/Editing/Pixabay.png') }}"
    imgesUrlFifteen="{{ asset('/images/Editing/PexelsVideo.png') }}"
    imgesUrlSixteen="{{ asset('/images/Editing/Videezy.jpg') }}"
    imgesUrlSeventeen="{{ asset('/images/Design/AdobeColor.png') }}"
    imgesUrlEighteen="{{ asset('/images/Design/envato.jpg') }}"
    imgesUrlNineteen="{{ asset('/images/Editing/MotionArray.png') }}"
    imgesUrlTwenty="{{ asset('/images/Editing/FrameIo.jpg') }}"
    imgesUrlTwentyOne="{{ asset('/images/Design/dribbble.png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Editing/ShareAE.jpg') }}"
    imgesUrlTwentyThree="{{ asset('/images/Editing/VFXDownload.webp') }}"
    imgesUrlTwentyFour="{{ asset('/images/Editing/FlexClip.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/Editing/Runway.png') }}"
    imgesUrlTwentySix="{{ asset('/images/Editing/WeVideo.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/Editing/WaveVideo.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/Editing/Renderforest.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/Editing/OpusClip.png') }}"
    imgesUrlThirty="{{ asset('/images/Editing/Pictory.png') }}"
    imgesUrlThirtyone="{{ asset('/images/Editing/Descript.jpeg') }}"
    imgesUrlThirtytwo="{{ asset('/images/Editing/Lumen5.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/Editing/Filmora.jpg') }}"
    imgesUrlThirtyfour="{{ asset('/images/Editing/Flixier.jpg') }}"
    imgesUrlThirtyfive="{{ asset('/images/Editing/Biteable.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/Editing/Animaker.jpg') }}"
    imgesUrlThirtyseven="{{ asset('/images/Editing/Shotcut.webp') }}"
    routeNameOne="Clipchamp" routeNameTwo="Photopea" routeNameThree="Kapwing" routeNameFour="AdobePremierePro" routeNameFive="DaVinciResolve" routeNameSix="CapCut" routeNameSeven="Canva" routeNameEight="VeedIo" routeNameNine="InVideo" routeNameTen="Animoto" routeNameEleven="Mixkit" routeNameTowlve="Freesound"
    routeNameThirteen="EpidemicSound" routeNameFourteen="Pixabay" routeNameFifteen="PexelsVideo" routeNameSixteen="Videezy" routeNameSeventeen="AdobeColor" routeNameEighteen="Envato" routeNameNineteen="MotionArray" routeNametwenty="FrameIo" routeNametwentyone="Dribbble" routeNametwentytwo="ShareAE" routeNametwentythree="VFXDownload"
    routeNametwentyfour="FlexClip" routeNametwentyfive="Runway" routeNametwentysix="WeVideo" routeNametwentyseven="WaveVideo" routeNametwentyeight="Renderforest" routeNametwentynine="OpusClip" routeNamethirty="Pictory" routeNamethirtyone="Descript" routeNamethirtytwo="Lumen5" routeNamethirtythree="Filmora"
    routeNamethirtyfour="Flixier" routeNamethirtyfive="Biteable" routeNamethirtysix="Animaker" routeNamethirtyseven="Shotcut">
</x-Pages>
