<x-pages pageTitle="Front End" pageTitleAll="Front End " title="Front End "
    imgesUrlOne="{{ asset('/images/Dev/FrontEnd/MDNWebDocs.webp') }}"
    imgesUrlTwo="{{ asset('/images/Dev/FrontEnd/StackBlitz.png') }}"
    imgesUrlThree="{{ asset('/images/Dev/FrontEnd/W3Schools.jpg') }}"
    imgesUrlFour="{{ asset('/images/Dev/FrontEnd/WebDev.png') }}"
    imgesUrlFive="{{ asset('/images/Dev/FrontEnd/FrontendMentor.png') }}"
    imgesUrlSix="{{ asset('/images/Dev/FrontEnd/CollectUI.jpg') }}"
    imgesUrlSeven="{{ asset('/images/Dev/FrontEnd/CSSTricks.jpg') }}"
    imgesUrlEight="{{ asset('/images/Dev/FrontEnd/Animista.jpg') }}"
    imgesUrlNine="{{ asset('/images/Dev/FrontEnd/UIGradients.png') }}"
    imgesUrlTen="{{ asset('/images/Dev/FrontEnd/Neumorphismio.webp') }}"
    imgesUrlEleven="{{ asset('/images/Dev/FrontEnd/Unsplash.png') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/FrontEnd/CodePen.png') }}"
    imgesUrlThirteen="{{ asset('/images/Dev/FrontEnd/CodeSandbox.png') }}"
    imgesUrlFourteen="{{ asset('/images/Dev/FrontEnd/GoogleFonts.png') }}"
    imgesUrlFifteen="{{ asset('/images/Dev/FrontEnd/FontAwesome.png') }}"
    imgesUrlSixteen="{{ asset('/images/Dev/FrontEnd/pexel.png') }}"
    imgesUrlSeventeen="{{ asset('/images/Dev/FrontEnd/RoadmapSh.png') }}"
    imgesUrlEighteen="{{ asset('/images/Dev/FrontEnd/HappyHues.png') }}"
    imgesUrlNineteen="{{ asset('/images/Dev/FrontEnd/UiverseIo.jpg') }}"
    imgesUrlTwenty="{{ asset('/images/Dev/FrontEnd/Coolors.png') }}"
    imgesUrlTwentyOne="{{ asset('/images/Dev/FrontEnd/caniuse.png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/FrontEnd/GitHub.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/Dev/FrontEnd/Netlify.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/Dev/FrontEnd/Vercel.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/Dev/FrontEnd/freeCodeCamp.png') }}"
    imgesUrlTwentySix="{{ asset('/images/Dev/FrontEnd/JSFiddle.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/Dev/FrontEnd/UniverseWebsiteBuilder.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/Dev/FrontEnd/MagicUI.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/Dev/FrontEnd/Bootstrap.jpg') }}"
    imgesUrlThirty="{{ asset('/images/Dev/FrontEnd/Tailwind.png') }}"
    imgesUrlThirtyone="{{ asset('/images/Dev/FrontEnd/Scrimba.jpg') }}"
    imgesUrlThirtytwo="{{ asset('/images/Dev/FrontEnd/OnePageLove.png') }}"
    imgesUrlThirtythree="{{ asset('/images/Dev/FrontEnd/LapaNinja.jpg') }}"
    imgesUrlThirtyfour="{{ asset('/images/Dev/FrontEnd/ResponsivelyApp.png') }}"
    imgesUrlThirtyfive="{{ asset('/images/Dev/FrontEnd/Figma.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/Dev/FrontEnd/PageSpeedInsights.png') }}"
    imgesUrlThirtyseven="{{ asset('/images/Dev/FrontEnd/DaisyUI.jpg') }}"
    routeNameOne="MDNWebDocs" routeNameTwo="StackBlitz" routeNameThree="W3Schools" routeNameFour="WebDev" routeNameFive="FrontendMentor" routeNameSix="CollectUI" routeNameSeven="CSSTricks" routeNameEight="Animista" routeNameNine="UIGradients" routeNameTen="Neumorphismio" routeNameEleven="Unsplash" routeNameTowlve="CodePen"
    routeNameThirteen="CodeSandbox" routeNameFourteen="GoogleFonts" routeNameFifteen="FontAwesome" routeNameSixteen="Pexel" routeNameSeventeen="RoadmapSh" routeNameEighteen="HappyHues" routeNameNineteen="UiverseIo" routeNametwenty="Coolors" routeNametwentyone="caniuse" routeNametwentytwo="GitHub" routeNametwentythree="Netlify"
    routeNametwentyfour="Vercel" routeNametwentyfive="freeCodeCamp" routeNametwentysix="JSFiddle" routeNametwentyseven="UniverseWebsiteBuilder" routeNametwentyeight="MagicUI" routeNametwentynine="Bootstrap" routeNamethirty="Tailwind" routeNamethirtyone="Scrimba" routeNamethirtytwo="OnePageLove" routeNamethirtythree="LapaNinja"
    routeNamethirtyfour="ResponsivelyApp" routeNamethirtyfive="Figma" routeNamethirtysix="PageSpeedInsights" routeNamethirtyseven="DaisyUI">
    <x-slot:PageTitle>
        Front End - Lap Tools Web
        </x-slot>
</x-pages>
