<x-pages pageTitle="Design" pageTitleAll="Design " title="Design "
    imgesUrlOne="{{ asset('/images/Design/Behance.jpg') }}"
    imgesUrlTwo="{{ asset('/images/Design/dribbble-logo.png') }}"
    imgesUrlThree="{{ asset('/images/Design/pinterest.gif') }}"
    imgesUrlFour="{{ asset('/images/Design/Awwwards.png') }}"
    imgesUrlFive="{{ asset('/images/Design/artstationLogo.jpg') }}"
    imgesUrlSix="{{ asset('/images/Design/Envato.jpg') }}"
    imgesUrlSeven="{{ asset('/images/Design/Canva.jpg') }}"
    imgesUrlEight="{{ asset('/images/Design/Designspiration.jpg') }}"
    imgesUrlNine="{{ asset('/images/Design/lottiefiles.jpg.jpg') }}"
    imgesUrlTen="{{ asset('/images/Design/Coolors.png') }}"
    imgesUrlEleven="{{ asset('/images/Design/Unsplash.png') }}"
    imgesUrlTwelve="{{ asset('/images/Design/Icons8.png') }}"
    imgesUrlThirteen="{{ asset('/images/Design/magnific.webp') }}"
    imgesUrlFourteen="{{ asset('/images/Design/Mobbin.jpg') }}"
    imgesUrlFifteen="{{ asset('/images/Design/Flaticon.png') }}"
    imgesUrlSixteen="{{ asset('/images/Design/unDraw.png') }}"
    imgesUrlSeventeen="{{ asset('/images/Design/AdobeColor.png') }}"
    imgesUrlEighteen="{{ asset('/images/Design/HappyHues.png') }}"
    imgesUrlNineteen="{{ asset('/images/Design/LSGraphics.webp') }}"
    imgesUrlTwenty="{{ asset('/images/Design/wordmark.png') }}"
    imgesUrlTwentyOne="{{ asset('/images/Design/LogoLounge.webp') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Design/khroma.jpg') }}"
    imgesUrlTwentyThree="{{ asset('/images/Design/Phosphor.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/Design/Logopond.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/Design/BrandNewLogo.webp') }}"
    imgesUrlTwentySix="{{ asset('/images/Design/99designs.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/Design/WorkingNotWorking.jpg') }}"
    imgesUrlTwentyEight="{{ asset('/images/Design/Vecteezy.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/Design/AdobeStock.jpg') }}"
    imgesUrlThirty="{{ asset('/images/Design/VistaCreate.png') }}"
    imgesUrlThirtyone="{{ asset('/images/Design/GraphicBurger.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/Design/pexel.png') }}"
    imgesUrlThirtythree="{{ asset('/images/Design/GoogleFonts.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/Design/mockupworld.jpg') }}"
    imgesUrlThirtyfive="{{ asset('/images/Design/RemoveBg.png') }}"
    imgesUrlThirtysix="{{ asset('/images/Design/TinyPNG.webp') }}"
    imgesUrlThirtyseven="{{ asset('/images/Design/blushDesign.png') }}"
    routeNameOne="Behance" routeNameTwo="Dribbble" routeNameThree="Pinterest" routeNameFour="Awwwards" routeNameFive="ArtStation" routeNameSix="Envato" routeNameSeven="Canva" routeNameEight="Designspiration" routeNameNine="Lottiefiles" routeNameTen="Coolors" routeNameEleven="Unsplash" routeNameTowlve="Icons8"
    routeNameThirteen="Magnific" routeNameFourteen="Mobbin" routeNameFifteen="Flaticon" routeNameSixteen="unDraw" routeNameSeventeen="AdobeColor" routeNameEighteen="HappyHues" routeNameNineteen="LSGraphics" routeNametwenty="wordmark" routeNametwentyone="LogoLounge" routeNametwentytwo="Khroma" routeNametwentythree="PhosphorIcons"
    routeNametwentyfour="Logopond" routeNametwentyfive="BrandNew" routeNametwentysix="D99designs" routeNametwentyseven="WorkingNotWorking" routeNametwentyeight="Vecteezy" routeNametwentynine="AdobeStock" routeNamethirty="VistaCreate" routeNamethirtyone="GraphicBurger" routeNamethirtytwo="Pexel" routeNamethirtythree="GoogleFonts"
    routeNamethirtyfour="MockupWorld" routeNamethirtyfive="RemoveBg" routeNamethirtysix="TinyPNG" routeNamethirtyseven="BlushDesign">
</x-pages>
