<x-pages pageTitle="Excel" pageTitleAll="Excel" title="Excel"
    imgesUrlOne="{{ asset('/images/office/Excel/MicrosoftExcelTraining.jpg') }}"
    imgesUrlTwo="{{ asset('/images/office/Excel/ExcelDon.jpg') }}"
    imgesUrlThree="{{ asset('/images/office/Excel/ExcelEasy.png') }}"
    imgesUrlFour="{{ asset('/images/office/Excel/ExcelJet.jpg') }}"
    imgesUrlFive="{{ asset('/images/office/Excel/Spreadsheeto.png') }}"
    imgesUrlSix="{{ asset('/images/office/Excel/MyOnlineTrainingHub.jpg') }}"
    imgesUrlSeven="{{ asset('/images/office/word/Vertex42.jpg') }}"
    imgesUrlEight="{{ asset('/images/office/Excel/Spreadsheet123.png') }}"
    imgesUrlNine="{{ asset('/images/office/word/Template.jpg') }}"
    imgesUrlTen="{{ asset('/images/office/word/iLovePDF.png') }}"
    imgesUrlEleven="{{ asset('/images/office/Excel/CloudConvert.jpg') }}"
    imgesUrlTwelve="{{ asset('/images/office/powerpoint/WPSOfficeTemplates.webp') }}"
    imgesUrlThirteen="{{ asset('/images/office/Excel/Datawrapper.png') }}"
    imgesUrlFourteen="{{ asset('/images/office/Excel/Flourish.png') }}"
    imgesUrlFifteen="{{ asset('/images/office/word/PDF24.jpg') }}"
    imgesUrlSixteen="{{ asset('/images/office/Excel/Convertio.png') }}"
    imgesUrlSeventeen="{{ asset('/images/office/Excel/OpenRefine.png') }}"
    imgesUrlEighteen="{{ asset('/images/Dev/AI/Kaggle.png') }}"
    imgesUrlNineteen="{{ asset('/images/Dev/Data/DataGov.png') }}"
    imgesUrlTwenty="{{ asset('/images/Dev/Data/OurWorldinData.png') }}"
    imgesUrlTwentyOne="{{ asset('/images/office/Excel/Airtable.png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/office/Excel/ZohoSheet.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/office/Excel/ONLYOFFICE.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/office/Excel/ExcelFormulaBot.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/office/Excel/formulasHq.png') }}"
    imgesUrlTwentySix="{{ asset('/images/office/Excel/AblebitsExcelBlog.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/office/Excel/GPTExcel.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/office/Excel/AjelixAI.jpg') }}"
    imgesUrlTwentyNine="{{ asset('/images/office/Excel/sheetAi.jpg') }}"
    imgesUrlThirty="{{ asset('/images/office/Excel/Indzara.png') }}"
    imgesUrlThirtyone="{{ asset('/images/office/Excel/ExcelDashboardSchool.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/office/Excel/Someka.png') }}"
    imgesUrlThirtythree="{{ asset('/images/office/Excel/Eloquens.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/office/Excel/QlikSense.jpg') }}"
    imgesUrlThirtyfive="{{ asset('/images/office/Excel/Plotly.png') }}"
    imgesUrlThirtysix="{{ asset('/images/office/Excel/ApacheSuperset.png') }}"
    imgesUrlThirtyseven="{{ asset('/images/office/Excel/Baserow.png') }}"
    routeNameOne="MicrosoftExcelTraining" routeNameTwo="ExcelDon" routeNameThree="ExcelEasy" routeNameFour="ExcelJet" routeNameFive="Spreadsheeto" routeNameSix="MyOnlineTrainingHub" routeNameSeven="Vertex42" routeNameEight="Spreadsheet123" routeNameNine="Template" routeNameTen="iLovePDF" routeNameEleven="CloudConvert" routeNameTowlve="WPSOfficeTemplates"
    routeNameThirteen="Datawrapper" routeNameFourteen="Flourish" routeNameFifteen="PDF24" routeNameSixteen="Convertio" routeNameSeventeen="OpenRefine" routeNameEighteen="Kaggle" routeNameNineteen="DataGov" routeNametwenty="OurWorldinData" routeNametwentyone="Airtable" routeNametwentytwo="ZohoSheet" routeNametwentythree="ONLYOFFICE"
    routeNametwentyfour="ExcelFormulaBot" routeNametwentyfive="formulasHq" routeNametwentysix="AblebitsExcelBlog" routeNametwentyseven="GPTExcel" routeNametwentyeight="AjelixAI" routeNametwentynine="sheetAi" routeNamethirty="Indzara" routeNamethirtyone="ExcelDashboardSchool" routeNamethirtytwo="Someka" routeNamethirtythree="Eloquens"
    routeNamethirtyfour="QlikSense" routeNamethirtyfive="Plotly" routeNamethirtysix="ApacheSuperset" routeNamethirtyseven="Baserow">
    <x-slot:PageTitle>
        Excel - Lap Tools Web
        </x-slot>
</x-pages>
