<x-pages-content pageTitle="Developers" contentOne="Front End"
    contentFourTwo="Back End "
    contentThree="Mobile App "
    contentFour="Game "
    contentFive="AI Development"
    contentSix="Data Science"
    contentSeven="UI/UX Design"
    contentEight="cyberSecurity"
    imgesUrlPagesOne="{{ asset('/images/Dev/FrontEnd/FrontEnd.png') }}"
    imgesUrlPagesTwo="{{ asset('/images/Dev/BackEnd/BackEnd.png') }}"
    imgesUrlPagesThree="{{ asset('/images/Dev/Mobile/MobileApp.png') }}"
    imgesUrlPagesFour="{{ asset('/images/Dev/Games/Game.png') }}"
    imgesUrlPagesFive="{{ asset('/images/Dev/AI/AI Developmen.png') }}"
    imgesUrlPagesSix="{{ asset('/images/Dev/Data/Data Science.png') }}"
    imgesUrlPagesSeven="{{ asset('/images/Dev/UI/UIUX.png') }}"
    imgesUrlPagesEight="{{ asset('/images/Dev/cyberSecurity/cyberSecurity.png') }}"
    routeNameOne="FrontEnd"
    routeNameTwo="BackEnd"
    routeNameThree="MobileApp"
    routeNameFour="GamesDevelopment"
    routeNameFive="AIDevelopment"
    routeNameSix="DataScience"
    routeNameSeven="UIDesign"
    routeNameEight="cyberSecurity"
    >
</x-pages-content>
