<x-pages pageTitle="Word" pageTitleAll="ًWord" title="Word"
    imgesUrlOne="{{ asset('/images/office/Word/Grammarly.png') }}"
    imgesUrlTwo="{{ asset('/images/office/Word/WordDon.png') }}"
    imgesUrlThree="{{ asset('/images/office/Word/QuillBot.png') }}"
    imgesUrlFour="{{ asset('/images/office/Word/LanguageTool.png') }}"
    imgesUrlFive="{{ asset('/images/office/Word/HemingwayEditor.jpg') }}"
    imgesUrlSix="{{ asset('/images/office/Word/Scribbr.png') }}"
    imgesUrlSeven="{{ asset('/images/office/Word/Zotero.jpg') }}"
    imgesUrlEight="{{ asset('/images/office/Word/Mendeley.png') }}"
    imgesUrlNine="{{ asset('/images/office/Word/CanvaDocs.png') }}"
    imgesUrlTen="{{ asset('/images/office/Word/TinyWowWordTools.jpg') }}"
    imgesUrlEleven="{{ asset('/images/office/Word/iLovePDF.png') }}"
    imgesUrlTwelve="{{ asset('/images/office/Word/ProWritingAid.jpg') }}"
    imgesUrlThirteen="{{ asset('/images/office/Word/DeepLWrite.png') }}"
    imgesUrlFourteen="{{ asset('/images/office/Word/Writesonic.jpg') }}"
    imgesUrlFifteen="{{ asset('/images/office/Word/RefWorks.jpg') }}"
    imgesUrlSixteen="{{ asset('/images/office/Word/CopyAi.jpg') }}"
    imgesUrlSeventeen="{{ asset('/images/office/Word/jasper.png') }}"
    imgesUrlEighteen="{{ asset('/images/office/Word/Rytr.jpg') }}"
    imgesUrlNineteen="{{ asset('/images/office/Word/Anyword.jpg') }}"
    imgesUrlTwenty="{{ asset('/images/office/Word/EndNote.jpg') }}"
    imgesUrlTwentyOne="{{ asset('/images/office/Word/Paperpile.webp') }}"
    imgesUrlTwentyTwo="{{ asset('/images/office/Word/Turnitin.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/office/Word/Copyscape.jpg') }}"
    imgesUrlTwentyFour="{{ asset('/images/office/Word/Template.jpg') }}"
    imgesUrlTwentyFive="{{ asset('/images/office/Word/Vertex42.jpg') }}"
    imgesUrlTwentySix="{{ asset('/images/office/Word/PoweredTemplate.jpg') }}"
    imgesUrlTwentySeven="{{ asset('/images/office/Word/PDF24.jpg') }}"
    imgesUrlTwentyEight="{{ asset('/images/office/Word/GoogleScholar.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/office/Word/ResearchGate.jpg') }}"
    imgesUrlThirty="{{ asset('/images/office/Word/SemanticScholar.jpg') }}"
    imgesUrlThirtyone="{{ asset('/images/office/Word/PubMed.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/office/Word/JSTOR.png') }}"
    imgesUrlThirtythree="{{ asset('/images/office/Word/TextFixer.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/office/Word/WordCounter.png') }}"
    imgesUrlThirtyfive="{{ asset('/images/office/Word/characterCountOnline.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/office/Word/Diffchecker.webp') }}"
    imgesUrlThirtyseven="{{ asset('/images/office/Word/WinMerge.jpg') }}"
    routeNameOne="Grammarly" routeNameTwo="WordDon" routeNameThree="QuillBot" routeNameFour="LanguageTool" routeNameFive="HemingwayEditor" routeNameSix="Scribbr" routeNameSeven="Zotero" routeNameEight="Mendeley" routeNameNine="CanvaDocs" routeNameTen="TinyWowWordTools" routeNameEleven="iLovePDF" routeNameTowlve="ProWritingAid"
    routeNameThirteen="DeepLWrite" routeNameFourteen="Writesonic" routeNameFifteen="RefWorks" routeNameSixteen="CopyAi" routeNameSeventeen="jasper" routeNameEighteen="Rytr" routeNameNineteen="Anyword" routeNametwenty="EndNote" routeNametwentyone="Paperpile" routeNametwentytwo="Turnitin" routeNametwentythree="Copyscape"
    routeNametwentyfour="Template" routeNametwentyfive="Vertex42" routeNametwentysix="PoweredTemplate" routeNametwentyseven="PDF24" routeNametwentyeight="GoogleScholar" routeNametwentynine="ResearchGate" routeNamethirty="SemanticScholar" routeNamethirtyone="PubMed" routeNamethirtytwo="JSTOR" routeNamethirtythree="TextFixer"
    routeNamethirtyfour="WordCounter" routeNamethirtyfive="characterCountOnline" routeNamethirtysix="Diffchecker" routeNamethirtyseven="WinMerge">
    <x-slot:PageTitle>
        Word- Lap Tools Web
        </x-slot>
</x-pages>
