<x-pages pageTitle="powerpoint" pageTitleAll="powerpoint" title="powerpoint"
    imgesUrlOne="{{ asset('/images/office/powerpoint/Slidesgo.png') }}"
    imgesUrlTwo="{{ asset('/images/office/powerpoint/PowerPointDon.jpg') }}"
    imgesUrlThree="{{ asset('/images/office/powerpoint/SlidesCarnival.jpg') }}"
    imgesUrlFour="{{ asset('/images/office/word/PoweredTemplate.jpg') }}"
    imgesUrlFive="{{ asset('/images/office/powerpoint/PresentationGO.png') }}"
    imgesUrlSix="{{ asset('/images/Design/Unsplash.png') }}"
    imgesUrlSeven="{{ asset('/images/Editing/PexelsVideo.png') }}"
    imgesUrlEight="{{ asset('/images/Editing/Pixabay.png') }}"
    imgesUrlNine="{{ asset('/images/Design/Flaticon.png') }}"
    imgesUrlTen="{{ asset('/images/office/powerpoint/TheNounProject.png') }}"
    imgesUrlEleven="{{ asset('/images/Design/Icons8.png') }}"
    imgesUrlTwelve="{{ asset('/images/Design/canva.jpg') }}"
    imgesUrlThirteen="{{ asset('/images/office/powerpoint/Visme.png') }}"
    imgesUrlFourteen="{{ asset('/images/office/powerpoint/infogram.png') }}"
    imgesUrlFifteen="{{ asset('/images/office/powerpoint/Gamma.png') }}"
    imgesUrlSixteen="{{ asset('/images/office/powerpoint/BeautifulAi.png') }}"
    imgesUrlSeventeen="{{ asset('/images/office/word/GoogleScholar.png') }}"
    imgesUrlEighteen="{{ asset('/images/office/word/ResearchGate.jpg') }}"
    imgesUrlNineteen="{{ asset('/images/office/word/SemanticScholar.jpg') }}"
    imgesUrlTwenty="{{ asset('/images/office/powerpoint/SlideModel.jpg') }}"
    imgesUrlTwentyOne="{{ asset('/images/office/powerpoint/FPPT (FreePowerPointTemplates).png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/office/powerpoint/Showeet.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/office/powerpoint/SlideHunter.jpg') }}"
    imgesUrlTwentyFour="{{ asset('/images/Design/envato.jpg') }}"
    imgesUrlTwentyFive="{{ asset('/images/office/powerpoint/Burst.png') }}"
    imgesUrlTwentySix="{{ asset('/images/office/powerpoint/Venngage.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/office/powerpoint/Piktochart.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/office/word/PubMed.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/office/word/JSTOR.png') }}"
    imgesUrlThirty="{{ asset('/images/office/powerpoint/SlideGeeks.jpg') }}"
    imgesUrlThirtyone="{{ asset('/images/office/powerpoint/TemplateMonster.jpg') }}"
    imgesUrlThirtytwo="{{ asset('/images/office/powerpoint/MicrosoftOfficeTemplates.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/office/powerpoint/StockSnap.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/office/powerpoint/WPSOfficeTemplates.webp') }}"
    imgesUrlThirtyfive="{{ asset('/images/office/powerpoint/SlidesMania.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/Design/magnific.webp') }}"
    imgesUrlThirtyseven="{{ asset('/images/office/powerpoint/docsGoogle.png') }}"
    routeNameOne="Slidesgo" routeNameTwo="PowerPointDon" routeNameThree="SlidesCarnival" routeNameFour="PoweredTemplate" routeNameFive="PresentationGO" routeNameSix="Unsplash" routeNameSeven="PexelsVideo" routeNameEight="Pixabay" routeNameNine="Flaticon" routeNameTen="TheNounProject" routeNameEleven="Icons8" routeNameTowlve="Canva"
    routeNameThirteen="Visme" routeNameFourteen="infogram" routeNameFifteen="Gamma" routeNameSixteen="BeautifulAi" routeNameSeventeen="GoogleScholar" routeNameEighteen="ResearchGate" routeNameNineteen="SemanticScholar" routeNametwenty="SlideModel" routeNametwentyone="FPPT" routeNametwentytwo="Showeet" routeNametwentythree="SlideHunter"
    routeNametwentyfour="Envato" routeNametwentyfive="Burst" routeNametwentysix="Venngage" routeNametwentyseven="Piktochart" routeNametwentyeight="PubMed" routeNametwentynine="JSTOR" routeNamethirty="SlideGeeks" routeNamethirtyone="TemplateMonster" routeNamethirtytwo="MicrosoftOfficeTemplates" routeNamethirtythree="StockSnap"
    routeNamethirtyfour="WPSOfficeTemplates" routeNamethirtyfive="SlidesMania" routeNamethirtysix="Magnific" routeNamethirtyseven="docsGoogle">
    <x-slot:PageTitle>
        powerpoint - Lap Tools Web
        </x-slot>
</x-pages>
