<x-Pages pageTitle="Animation And 3D" pageTitleAll="AnimationAnd3D" title="Animation And 3D"
    imgesUrlOne="{{ asset('/images/AnimationAnd3D/BlenderStudio.png') }}"
    imgesUrlTwo="{{ asset('/images/AnimationAnd3D/Spline.png') }}"
    imgesUrlThree="{{ asset('/images/AnimationAnd3D/CGCookie.jpg') }}"
    imgesUrlFour="{{ asset('/images/AnimationAnd3D/Blender.png') }}"
    imgesUrlFive="{{ asset('/images/AnimationAnd3D/AutodeskMaya.jpg') }}"
    imgesUrlSix="{{ asset('/images/AnimationAnd3D/Autodesk3dsMax.webp') }}"
    imgesUrlSeven="{{ asset('/images/AnimationAnd3D/Houdini.jpg') }}"
    imgesUrlEight="{{ asset('/images/AnimationAnd3D/ZBrush.png') }}"
    imgesUrlNine="{{ asset('/images/Dev/Games/UnrealEngine.png') }}"
    imgesUrlTen="{{ asset('/images/Dev/Games/Unity.jpg') }}"
    imgesUrlEleven="{{ asset('/images/AnimationAnd3D/AnimSchool.jpg') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/Games/Sketchfab.png') }}"
    imgesUrlThirteen="{{ asset('/images/Dev/Games/CGTrader.png') }}"
    imgesUrlFourteen="{{ asset('/images/Dev/Games/TurboSquid.png') }}"
    imgesUrlFifteen="{{ asset('/images/AnimationAnd3D/RenderHub.png') }}"
    imgesUrlSixteen="{{ asset('/images/AnimationAnd3D/Free3D.jpg') }}"
    imgesUrlSeventeen="{{ asset('/images/AnimationAnd3D/BlendSwap.png') }}"
    imgesUrlEighteen="{{ asset('/images/AnimationAnd3D/PolyHaven.png') }}"
    imgesUrlNineteen="{{ asset('/images/AnimationAnd3D/ambientCG.png') }}"
    imgesUrlTwenty="{{ asset('/images/AnimationAnd3D/TexturesCom.jpg') }}"
    imgesUrlTwentyOne="{{ asset('/images/AnimationAnd3D/3DTexturesMe.jpg') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/Games/Mixamo.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/AnimationAnd3D/Reallusion.jpg') }}"
    imgesUrlTwentyFour="{{ asset('/images/AnimationAnd3D/QuixelMegascans.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/AnimationAnd3D/Daz3D.jpg') }}"
    imgesUrlTwentySix="{{ asset('/images/AnimationAnd3D/MetaHumanCreator.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/AnimationAnd3D/ActionVFX.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/AnimationAnd3D/ProductionCrate.jpg') }}"
    imgesUrlTwentyNine="{{ asset('/images/AnimationAnd3D/VideoCopilot.jpg') }}"
    imgesUrlThirty="{{ asset('/images/AnimationAnd3D/ChaosVRay.png') }}"
    imgesUrlThirtyone="{{ asset('/images/AnimationAnd3D/CoronaRenderer.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/AnimationAnd3D/OctaneRender.png') }}"
    imgesUrlThirtythree="{{ asset('/images/AnimationAnd3D/Redshift.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/AnimationAnd3D/SchoolofMotion.avif') }}"
    imgesUrlThirtyfive="{{ asset('/images/AnimationAnd3D/MotionDesignSchool.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/AnimationAnd3D/Kaiber.jpg') }}"
    imgesUrlThirtyseven="{{ asset('/images/AnimationAnd3D/MeshyAI.png') }}"
    routeNameOne="BlenderStudio" routeNameTwo="Spline" routeNameThree="CGCookie" routeNameFour="Blender" routeNameFive="AutodeskMaya" routeNameSix="Autodesk3dsMax" routeNameSeven="Houdini" routeNameEight="ZBrush" routeNameNine="UnrealEngine" routeNameTen="Unity" routeNameEleven="AnimSchool" routeNameTowlve="Sketchfab"
    routeNameThirteen="CGTrader" routeNameFourteen="TurboSquid" routeNameFifteen="RenderHub" routeNameSixteen="Free3D" routeNameSeventeen="BlendSwap" routeNameEighteen="PolyHaven" routeNameNineteen="ambientCG" routeNametwenty="TexturesCom" routeNametwentyone="TexturesMe3D" routeNametwentytwo="Mixamo" routeNametwentythree="Reallusion"
    routeNametwentyfour="QuixelMegascans" routeNametwentyfive="Daz3D" routeNametwentysix="MetaHumanCreator" routeNametwentyseven="ActionVFX" routeNametwentyeight="ProductionCrate" routeNametwentynine="VideoCopilot" routeNamethirty="ChaosVRay" routeNamethirtyone="CoronaRenderer" routeNamethirtytwo="OctaneRender" routeNamethirtythree="Redshift"
    routeNamethirtyfour="SchoolofMotion" routeNamethirtyfive="MotionDesignSchool" routeNamethirtysix="Kaiber" routeNamethirtyseven="MeshyAI">
</x-Pages>
