<x-pages pageTitle="GamsDev" pageTitleAll="GamsDev " title="GamsDev "
    imgesUrlOne="{{ asset('/images/Dev/Games/Unity.jpg') }}"
    imgesUrlTwo="{{ asset('/images/Dev/Games/Construct.webp') }}"
    imgesUrlThree="{{ asset('/images/Dev/Games/UnrealEngine.png') }}"
    imgesUrlFour="{{ asset('/images/Dev/Games/GodotEngine.png') }}"
    imgesUrlFive="{{ asset('/images/Dev/Games/ItchIo.png') }}"
    imgesUrlSix="{{ asset('/images/Dev/Games/Sketchfab.png') }}"
    imgesUrlSeven="{{ asset('/images/Dev/Games/TurboSquid.png') }}"
    imgesUrlEight="{{ asset('/images/Dev/Games/OpenGameArt.jpg') }}"
    imgesUrlNine="{{ asset('/images/Dev/Games/Freesound.png') }}"
    imgesUrlTen="{{ asset('/images/Dev/Games/Soniss.jpg') }}"
    imgesUrlEleven="{{ asset('/images/Dev/Games/Incompetech.png') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/Games/StackExchange.jpg') }}"
    imgesUrlThirteen="{{ asset('/images/Dev/Games/GameDeveloperWeb.png') }}"
    imgesUrlFourteen="{{ asset('/images/Dev/Games/GameMaker.png') }}"
    imgesUrlFifteen="{{ asset('/images/Dev/Games/UnityLearn.png') }}"
    imgesUrlSixteen="{{ asset('/images/Dev/Games/brackeys.jpg') }}"
    imgesUrlSeventeen="{{ asset('/images/Dev/Games/KenneyAssets.png') }}"
    imgesUrlEighteen="{{ asset('/images/Dev/Games/PolyPizza.png') }}"
    imgesUrlNineteen="{{ asset('/images/Dev/Games/IndieDB.jpg') }}"
    imgesUrlTwenty="{{ asset('/images/Dev/Games/Steamworks.jpg') }}"
    imgesUrlTwentyOne="{{ asset('/images/Dev/Games/GameDesignLounge.png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/Games/CGTrader.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/Dev/Games/Mixamo.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/Dev/Games/Cascadeur.jpg') }}"
    imgesUrlTwentyFive="{{ asset('/images/Dev/Mobile/freeCodeCamp.png') }}"
    imgesUrlTwentySix="{{ asset('/images/Dev/Games/InworldAI.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/Dev/Games/LeonardoAI.jpg') }}"
    imgesUrlTwentyEight="{{ asset('/images/Dev/Games/Phaser.jpg') }}"
    imgesUrlTwentyNine="{{ asset('/images/Dev/Games/BabylonJs.png') }}"
    imgesUrlThirty="{{ asset('/images/Dev/Games/ThreeJs.png') }}"
    imgesUrlThirtyone="{{ asset('/images/Dev/Games/PlayFab.jpg') }}"
    imgesUrlThirtytwo="{{ asset('/images/Dev/Games/GameAnalytics.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/Dev/Games/Level80.jpg') }}"
    imgesUrlThirtyfour="{{ asset('/images/Dev/Games/PlasticSCM.png') }}"
    imgesUrlThirtyfive="{{ asset('/images/Dev/Games/Perforce.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/Dev/Games/RedBlobGames.png') }}"
    imgesUrlThirtyseven="{{ asset('/images/Dev/Games/GlobalGameJam.png') }}"
    routeNameOne="Unity" routeNameTwo="Construct" routeNameThree="UnrealEngine" routeNameFour="GodotEngine" routeNameFive="ItchIo" routeNameSix="Sketchfab" routeNameSeven="TurboSquid" routeNameEight="OpenGameArt" routeNameNine="Freesound" routeNameTen="Soniss" routeNameEleven="Incompetech" routeNameTowlve="StackExchange"
    routeNameThirteen="GameDeveloperWeb" routeNameFourteen="GameMaker" routeNameFifteen="UnityLearn" routeNameSixteen="brackeys" routeNameSeventeen="KenneyAssets" routeNameEighteen="PolyPizza" routeNameNineteen="IndieDB" routeNametwenty="Steamworks" routeNametwentyone="GameDesignLounge" routeNametwentytwo="CGTrader" routeNametwentythree="Mixamo"
    routeNametwentyfour="Cascadeur" routeNametwentyfive="freeCodeCamp" routeNametwentysix="InworldAI" routeNametwentyseven="LeonardoAI" routeNametwentyeight="Phaser" routeNametwentynine="BabylonJs" routeNamethirty="ThreeJs" routeNamethirtyone="PlayFab" routeNamethirtytwo="GameAnalytics" routeNamethirtythree="Level80"
    routeNamethirtyfour="PlasticSCM" routeNamethirtyfive="Perforce" routeNamethirtysix="RedBlobGames" routeNamethirtyseven="GlobalGameJam">
    <x-slot:PageTitle>
        GamsDev - Lap Tools Web
        </x-slot>
</x-pages>
