<x-Pages pageTitle="Photos And Videos"  title="Photos And Videos"
    imgesUrlOne="{{ asset('/images/AIROOM/PhotosAndvideos/Midjourney.jpg') }}"
    imgesUrlTwo="{{ asset('/images/AIROOM/PhotosAndvideos/StableDiffusion.jpg') }}"
    imgesUrlThree="{{ asset('/images/AIROOM/ChatAI/ChatGPT.png') }}"
    imgesUrlFour="{{ asset('/images/AIROOM/PhotosAndvideos/AdobeFirefly.png') }}"
    imgesUrlFive="{{ asset('/images/AIROOM/PhotosAndvideos/Ideogram.png') }}"
    imgesUrlSix="{{ asset('/images/AIROOM/PhotosAndvideos/Recraft.jpg') }}"
    imgesUrlSeven="{{ asset('/images/AIROOM/PhotosAndvideos/Playground.jpg') }}"
    imgesUrlEight="{{ asset('/images/AIROOM/PhotosAndvideos/NightCafe.png') }}"
    imgesUrlNine="{{ asset('/images/AIROOM/PhotosAndvideos/MageSpace.png') }}"
    imgesUrlTen="{{ asset('/images/Editing/Runway.png') }}"
    imgesUrlEleven="{{ asset('/images/Dev/AI/GoogleAIStudio.png') }}"
    imgesUrlTwelve="{{ asset('/images/AIROOM/PhotosAndvideos/KlingAI.jpg') }}"
    imgesUrlThirteen="{{ asset('/images/AIROOM/PhotosAndvideos/HailuoAI.jpg') }}"
    imgesUrlFourteen="{{ asset('/images/AIROOM/PhotosAndvideos/Pika.webp') }}"
    imgesUrlFifteen="{{ asset('/images/AIROOM/PhotosAndvideos/LumaDreamMachine.png') }}"
    imgesUrlSixteen="{{ asset('/images/AIROOM/PhotosAndvideos/PixVerseAI.jpg') }}"
    imgesUrlSeventeen="{{ asset('/images/Editing/InVideo.webp') }}"
    imgesUrlEighteen="{{ asset('/images/AIROOM/PhotosAndvideos/HeyGen.png') }}"
    imgesUrlNineteen="{{ asset('/images/AIROOM/PhotosAndvideos/Synthesia.jpg') }}"
    imgesUrlTwenty="{{ asset('/images/AIROOM/ChatAI/Gemini.jpg') }}"
    imgesUrlTwentyOne="{{ asset('/images/AIROOM/PhotosAndvideos/nanobanana.png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/Games/LeonardoAI.jpg') }}"
    imgesUrlTwentyThree="{{ asset('/images/AIROOM/PhotosAndvideos/TensorArt.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/AIROOM/PhotosAndvideos/Civitai.jpg') }}"
    imgesUrlTwentyFive="{{ asset('/images/AIROOM/PhotosAndvideos/Craiyon.webp') }}"
    imgesUrlTwentySix="{{ asset('/images/AIROOM/PhotosAndvideos/StarryAI.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/AIROOM/PhotosAndvideos/Artbreeder.jpg') }}"
    imgesUrlTwentyEight="{{ asset('/images/AIROOM/PhotosAndvideos/FotorAI.jpg') }}"
    imgesUrlTwentyNine="{{ asset('/images/AIROOM/PhotosAndvideos/DeepAI.png') }}"
    imgesUrlThirty="{{ asset('/images/AIROOM/PhotosAndvideos/ImagineArt.jpg') }}"
    imgesUrlThirtyone="{{ asset('/images/AIROOM/PhotosAndvideos/GetimgAi.webp') }}"
    imgesUrlThirtytwo="{{ asset('/images/AIROOM/PhotosAndvideos/SeaArtAI.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/AIROOM/PhotosAndvideos/OpenArt.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/AIROOM/PhotosAndvideos/DzineAI.png') }}"
    imgesUrlThirtyfive="{{ asset('/images/AIROOM/PhotosAndvideos/HaiperAI.png') }}"
    imgesUrlThirtysix="{{ asset('/images/AIROOM/PhotosAndvideos/ViduAI.jpg') }}"
    imgesUrlThirtyseven="{{ asset('/images/AIROOM/PhotosAndvideos/HiggsfieldAI.jpg') }}"
    routeNameOne="Midjourney" routeNameTwo="StableDiffusion" routeNameThree="ChatGPT" routeNameFour="AdobeFirefly" routeNameFive="Ideogram" routeNameSix="Recraft" routeNameSeven="Playground" routeNameEight="NightCafe" routeNameNine="MageSpace" routeNameTen="Runway" routeNameEleven="GoogleAIStudio" routeNameTowlve="KlingAI"
    routeNameThirteen="HailuoAI" routeNameFourteen="Pika" routeNameFifteen="LumaDreamMachine" routeNameSixteen="PixVerseAI" routeNameSeventeen="InVideo" routeNameEighteen="HeyGen" routeNameNineteen="Synthesia" routeNametwenty="Gemini" routeNametwentyone="nanobanana" routeNametwentytwo="LeonardoAI" routeNametwentythree="TensorArt"
    routeNametwentyfour="Civitai" routeNametwentyfive="Craiyon" routeNametwentysix="StarryAI" routeNametwentyseven="Artbreeder" routeNametwentyeight="FotorAI" routeNametwentynine="DeepAI" routeNamethirty="ImagineArt" routeNamethirtyone="GetimgAi" routeNamethirtytwo="SeaArtAI" routeNamethirtythree="OpenArt"
    routeNamethirtyfour="DzineAI" routeNamethirtyfive="HaiperAI" routeNamethirtysix="ViduAI" routeNamethirtyseven="HiggsfieldAI">
</x-Pages>
