<x-pages pageTitle="Automation"  title="Automation"
    imgesUrlOne="{{ asset('/images/AIROOM/Automation/Zapier.png') }}"
    imgesUrlTwo="{{ asset('/images/AIROOM/Automation/nOps.png') }}"
    imgesUrlThree="{{ asset('/images/AIROOM/Automation/Make.png') }}"
    imgesUrlFour="{{ asset('/images/AIROOM/Automation/n8n.png') }}"
    imgesUrlFive="{{ asset('/images/AIROOM/Automation/Pipedream.png') }}"
    imgesUrlSix="{{ asset('/images/AIROOM/Automation/IFTTT.png') }}"
    imgesUrlSeven="{{ asset('/images/AIROOM/Automation/RelayApp.jpg') }}"
    imgesUrlEight="{{ asset('/images/AIROOM/Automation/Albato.jpg') }}"
    imgesUrlNine="{{ asset('/images/AIROOM/Automation/Integrately.png') }}"
    imgesUrlTen="{{ asset('/images/AIROOM/Automation/AgentGPT.jpg') }}"
    imgesUrlEleven="{{ asset('/images/AIROOM/Automation/AutoGPT.png') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/AI/CrewAI.png') }}"
    imgesUrlThirteen="{{ asset('/images/AIROOM/Automation/Flowise.png') }}"
    imgesUrlFourteen="{{ asset('/images/AIROOM/Automation/Dify.png') }}"
    imgesUrlFifteen="{{ asset('/images/AIROOM/Automation/ActiveCampaign.jpg') }}"
    imgesUrlSixteen="{{ asset('/images/AIROOM/Automation/Mailchimp.png') }}"
    imgesUrlSeventeen="{{ asset('/images/AIROOM/Automation/Brevo.png') }}"
    imgesUrlEighteen="{{ asset('/images/AIROOM/Automation/HubSpot.png') }}"
    imgesUrlNineteen="{{ asset('/images/AIROOM/Automation/Buffer.png') }}"
    imgesUrlTwenty="{{ asset('/images/AIROOM/Automation/Publer.webp') }}"
    imgesUrlTwentyOne="{{ asset('/images/AIROOM/Automation/Metricool.jpg') }}"
    imgesUrlTwentyTwo="{{ asset('/images/AIROOM/Automation/UiPath.jpg') }}"
    imgesUrlTwentyThree="{{ asset('/images/AIROOM/Automation/AutomationAnywhere.jpg') }}"
    imgesUrlTwentyFour="{{ asset('/images/AIROOM/Automation/Robocorp.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/AIROOM/Automation/LindyAI.jpg') }}"
    imgesUrlTwentySix="{{ asset('/images/AIROOM/Automation/Gumloop.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/AIROOM/Automation/Bardeen.jpg') }}"
    imgesUrlTwentyEight="{{ asset('/images/AIROOM/Automation/Airtop.jpg') }}"
    imgesUrlTwentyNine="{{ asset('/images/AIROOM/Automation/TaskadeAIAgents.jpg') }}"
    imgesUrlThirty="{{ asset('/images/AIROOM/Automation/Workato.png') }}"
    imgesUrlThirtyone="{{ asset('/images/AIROOM/Automation/TrayAi.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/AIROOM/Automation/RelevanceAI.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/AIROOM/Automation/SuperAGI.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/AIROOM/Automation/LangChain.jpg') }}"
    imgesUrlThirtyfive="{{ asset('/images/AIROOM/Automation/Temporal.png') }}"
    imgesUrlThirtysix="{{ asset('/images/AIROOM/Automation/Kestra.png') }}"
    imgesUrlThirtyseven="{{ asset('/images/AIROOM/Automation/Glide.png') }}"
    routeNameOne="Zapier" routeNameTwo="nOps" routeNameThree="Make" routeNameFour="n8n" routeNameFive="Pipedream" routeNameSix="IFTTT" routeNameSeven="RelayApp" routeNameEight="Albato" routeNameNine="Integrately" routeNameTen="AgentGPT" routeNameEleven="AutoGPT" routeNameTowlve="CrewAI"
    routeNameThirteen="Flowise" routeNameFourteen="Dify" routeNameFifteen="ActiveCampaign" routeNameSixteen="Mailchimp" routeNameSeventeen="Brevo" routeNameEighteen="HubSpot" routeNameNineteen="Buffer" routeNametwenty="Publer" routeNametwentyone="Metricool" routeNametwentytwo="UiPath" routeNametwentythree="AutomationAnywhere"
    routeNametwentyfour="Robocorp" routeNametwentyfive="LindyAI" routeNametwentysix="Gumloop" routeNametwentyseven="Bardeen" routeNametwentyeight="Airtop" routeNametwentynine="TaskadeAIAgents" routeNamethirty="Workato" routeNamethirtyone="TrayAi" routeNamethirtytwo="RelevanceAI" routeNamethirtythree="SuperAGI"
    routeNamethirtyfour="LangChain" routeNamethirtyfive="Temporal" routeNamethirtysix="Kestra" routeNamethirtyseven="Glide">
</x-pages>
