<x-pages pageTitle="Back End" pageTitleAll="Back End " title="Back End "
    imgesUrlOne="{{ asset('/images/Dev/BackEnd/DrawIo.png') }}"
    imgesUrlTwo="{{ asset('/images/Dev/BackEnd/Insomnia.png') }}"
    imgesUrlThree="{{ asset('/images/Dev/BackEnd/W3Schools.jpg') }}"
    imgesUrlFour="{{ asset('/images/Dev/BackEnd/RoadmapSh.png') }}"
    imgesUrlFive="{{ asset('/images/Dev/BackEnd/MDNWebDocs.webp') }}"
    imgesUrlSix="{{ asset('/images/Dev/BackEnd/DevDocsIo.jpg') }}"
    imgesUrlSeven="{{ asset('/images/Dev/BackEnd/Hoppscotch.jpg') }}"
    imgesUrlEight="{{ asset('/images/Dev/BackEnd/Postman.png') }}"
    imgesUrlNine="{{ asset('/images/Dev/BackEnd/JSONPlaceholder.png') }}"
    imgesUrlTen="{{ asset('/images/Dev/BackEnd/Regex101.jpg') }}"
    imgesUrlEleven="{{ asset('/images/Dev/BackEnd/dbdiagramIo.ico') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/BackEnd/ByteByteGo.png') }}"
    imgesUrlThirteen="{{ asset('/images/Dev/BackEnd/EraserIo.ico') }}"
    imgesUrlFourteen="{{ asset('/images/Dev/BackEnd/Excalidraw.png') }}"
    imgesUrlFifteen="{{ asset('/images/Dev/BackEnd/Firebase.png') }}"
    imgesUrlSixteen="{{ asset('/images/Dev/BackEnd/Supabase.jpg') }}"
    imgesUrlSeventeen="{{ asset('/images/Dev/BackEnd/Railway.png') }}"
    imgesUrlEighteen="{{ asset('/images/Dev/BackEnd/Render.png') }}"
    imgesUrlNineteen="{{ asset('/images/Dev/BackEnd/OWASP (Cheat Sheet Series).png') }}"
    imgesUrlTwenty="{{ asset('/images/Dev/BackEnd/K6Io.png') }}"
    imgesUrlTwentyOne="{{ asset('/images/Dev/BackEnd/Stack Overflow.png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/BackEnd/GitHub.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/Dev/BackEnd/GeeksforGeeks.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/Dev/BackEnd/Vercel.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/Dev/BackEnd/freeCodeCamp.png') }}"
    imgesUrlTwentySix="{{ asset('/images/Dev/BackEnd/Swagger.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/Dev/BackEnd/MongoDB.jpg') }}"
    imgesUrlTwentyEight="{{ asset('/images/Dev/BackEnd/MySQL.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/Dev/BackEnd/PostgreSQL.png') }}"
    imgesUrlThirty="{{ asset('/images/Dev/BackEnd/Redis.png') }}"
    imgesUrlThirtyone="{{ asset('/images/Dev/BackEnd/Heroku.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/Dev/BackEnd/DigitalOcean.png') }}"
    imgesUrlThirtythree="{{ asset('/images/Dev/BackEnd/JWTIo.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/Dev/BackEnd/HaveIBeenPwned.png') }}"
    imgesUrlThirtyfive="{{ asset('/images/Dev/BackEnd/Docker.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/Dev/BackEnd/Cloudinary.png') }}"
    imgesUrlThirtyseven="{{ asset('/images/Dev/BackEnd/Spatie.png') }}"
    routeNameOne="DrawIo" routeNameTwo="Insomnia" routeNameThree="dbdiagramIo" routeNameFour="WebDev" routeNameFive="FrontendMentor" routeNameSix="DevDocsIo" routeNameSeven="Hoppscotch" routeNameEight="Postman" routeNameNine="JSONPlaceholder" routeNameTen="Regex101" routeNameEleven="dbdiagramIo" routeNameTowlve="ByteByteGo"
    routeNameThirteen="EraserIo" routeNameFourteen="Excalidraw" routeNameFifteen="Firebase" routeNameSixteen="Supabase" routeNameSeventeen="Railway" routeNameEighteen="Render" routeNameNineteen="OWASP" routeNametwenty="K6Io" routeNametwentyone="StackOverflow" routeNametwentytwo="GitHub" routeNametwentythree="GeeksforGeeks"
    routeNametwentyfour="Vercel" routeNametwentyfive="freeCodeCamp" routeNametwentysix="Swagger" routeNametwentyseven="MongoDB" routeNametwentyeight="MySQL" routeNametwentynine="PostgreSQL" routeNamethirty="Redis" routeNamethirtyone="Heroku" routeNamethirtytwo="DigitalOcean" routeNamethirtythree="JWTIo"
    routeNamethirtyfour="HaveIBeenPwned" routeNamethirtyfive="Docker" routeNamethirtysix="Cloudinary" routeNamethirtyseven="Spatie">
    <x-slot:PageTitle>
        Back End - Lap Tools Web
        </x-slot>
</x-pages>
