<x-pages pageTitle="Mobile App" pageTitleAll="Mobile App " title="Mobile App "
    imgesUrlOne="{{ asset('/images/Dev/Mobile/AndroidDevelopers.png') }}"
    imgesUrlTwo="{{ asset('/images/Dev/Mobile/AppGyver.png') }}"
    imgesUrlThree="{{ asset('/images/Dev/Mobile/AppleDeveloper.jpg') }}"
    imgesUrlFour="{{ asset('/images/Dev/Mobile/FlutterDev.jpg') }}"
    imgesUrlFive="{{ asset('/images/Dev/Mobile/React NativeDev.png') }}"
    imgesUrlSix="{{ asset('/images/Dev/Mobile/pubDev.png') }}"
    imgesUrlSeven="{{ asset('/images/Dev/Mobile/npm.png') }}"
    imgesUrlEight="{{ asset('/images/Dev/Mobile/GitHub.png') }}"
    imgesUrlNine="{{ asset('/images/Dev/Mobile/MaterialDesign.png') }}"
    imgesUrlTen="{{ asset('/images/Dev/Mobile/FontAwesome.png') }}"
    imgesUrlEleven="{{ asset('/images/Dev/Mobile/lottiefiles.jpg.jpg') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/Mobile/Flaticon.png') }}"
    imgesUrlThirteen="{{ asset('/images/Dev/Mobile/Firebase.png') }}"
    imgesUrlFourteen="{{ asset('/images/Dev/Mobile/Postman.png') }}"
    imgesUrlFifteen="{{ asset('/images/Dev/Mobile/RiveApp.jpg') }}"
    imgesUrlSixteen="{{ asset('/images/Dev/Mobile/v0Dev.png') }}"
    imgesUrlSeventeen="{{ asset('/images/Dev/Mobile/RoadmapSh.png') }}"
    imgesUrlEighteen="{{ asset('/images/Dev/Mobile/Codemagic.png') }}"
    imgesUrlNineteen="{{ asset('/images/Dev/Mobile/ExpoApplicationServices.png') }}"
    imgesUrlTwenty="{{ asset('/images/Dev/Mobile/AppIcon Generator.png') }}"
    imgesUrlTwentyOne="{{ asset('/images/Dev/Mobile/Haikei.webp') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/Mobile/Diawi.jpg') }}"
    imgesUrlTwentyThree="{{ asset('/images/Dev/Mobile/BrowserStack.jpg') }}"
    imgesUrlTwentyFour="{{ asset('/images/Dev/Mobile/JSONCrack.jpg') }}"
    imgesUrlTwentyFive="{{ asset('/images/Dev/Mobile/freeCodeCamp.png') }}"
    imgesUrlTwentySix="{{ asset('/images/Dev/Mobile/Mockoon.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/Dev/Mobile/mockapi.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/Dev/Mobile/DataAi.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/Dev/Mobile/Appradar.jpg') }}"
    imgesUrlThirty="{{ asset('/images/Dev/Mobile/RevenueCat.png') }}"
    imgesUrlThirtyone="{{ asset('/images/Dev/Mobile/OneSignal.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/Dev/Mobile/AppFollow.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/Dev/Mobile/SensorTower.jpg') }}"
    imgesUrlThirtyfour="{{ asset('/images/Dev/Mobile/medium.webp') }}"
    imgesUrlThirtyfive="{{ asset('/images/Dev/Mobile/FlutterGems.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/Dev/Mobile/Kotlinlang.jpg') }}"
    imgesUrlThirtyseven="{{ asset('/images/Dev/Mobile/swift.jpg') }}"
    routeNameOne="AndroidDevelopers" routeNameTwo="AppGyver" routeNameThree="AppleDeveloper" routeNameFour="FlutterDev" routeNameFive="ReactNativeDev" routeNameSix="pubDev" routeNameSeven="npm" routeNameEight="GitHub" routeNameNine="MaterialDesign" routeNameTen="FontAwesome" routeNameEleven="Lottiefiles" routeNameTowlve="Flaticon"
    routeNameThirteen="Firebase" routeNameFourteen="Postman" routeNameFifteen="RiveApp" routeNameSixteen="v0Dev" routeNameSeventeen="RoadmapSh" routeNameEighteen="Codemagic" routeNameNineteen="ExpoApplicationServices" routeNametwenty="AppIconGenerator" routeNametwentyone="Haikei" routeNametwentytwo="Diawi" routeNametwentythree="BrowserStack"
    routeNametwentyfour="JSONCrack" routeNametwentyfive="freeCodeCamp" routeNametwentysix="Mockoon" routeNametwentyseven="mockapi" routeNametwentyeight="DataAi" routeNametwentynine="Appradar" routeNamethirty="RevenueCat" routeNamethirtyone="OneSignal" routeNamethirtytwo="AppFollow" routeNamethirtythree="SensorTower"
    routeNamethirtyfour="medium" routeNamethirtyfive="FlutterGems" routeNamethirtysix="Kotlinlang" routeNamethirtyseven="swift">
    <x-slot:PageTitle>
        Mobile App - Lap Tools Web
        </x-slot>
</x-pages>
