<x-pages pageTitle="cyberSecurity" pageTitleAll="cyberSecurity" title="cyberSecurity"
    imgesUrlOne="{{ asset('/images/Dev/cyberSecurity/TryHackMe.jpg') }}"
    imgesUrlTwo="{{ asset('/images/Dev/cyberSecurity/MITREATTCK.png') }}"
    imgesUrlThree="{{ asset('/images/Dev/cyberSecurity/HackTheBox.jpg') }}"
    imgesUrlFour="{{ asset('/images/Dev/BackEnd/RoadmapSh.png') }}"
    imgesUrlFive="{{ asset('/images/Dev/cyberSecurity/PortSwiggerWebSecurityAcademy.jpg') }}"
    imgesUrlSix="{{ asset('/images/Dev/cyberSecurity/OverTheWire.png') }}"
    imgesUrlSeven="{{ asset('/images/Dev/cyberSecurity/picoCTF.jpg') }}"
    imgesUrlEight="{{ asset('/images/Dev/cyberSecurity/CTFtime.png') }}"
    imgesUrlNine="{{ asset('/images/Dev/cyberSecurity/HackerOne.png') }}"
    imgesUrlTen="{{ asset('/images/Dev/cyberSecurity/Bugcrowd.jpg') }}"
    imgesUrlEleven="{{ asset('/images/Dev/cyberSecurity/TheHackerNews.jpg') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/cyberSecurity/CVEMitre.jpg') }}"
    imgesUrlThirteen="{{ asset('/images/Dev/cyberSecurity/BleepingComputer.jpg') }}"
    imgesUrlFourteen="{{ asset('/images/Dev/cyberSecurity/CyberDefenders.jpg') }}"
    imgesUrlFifteen="{{ asset('/images/Dev/cyberSecurity/LetsDefend.png') }}"
    imgesUrlSixteen="{{ asset('/images/Dev/cyberSecurity/VulnHub.png') }}"
    imgesUrlSeventeen="{{ asset('/images/Dev/cyberSecurity/OffSecLearningLibrary.jpg') }}"
    imgesUrlEighteen="{{ asset('/images/Dev/cyberSecurity/Cybrary.png') }}"
    imgesUrlNineteen="{{ asset('/images/Dev/BackEnd/OWASP (Cheat Sheet Series).png') }}"
    imgesUrlTwenty="{{ asset('/images/Dev/cyberSecurity/AntisyphonTraining.png') }}"
    imgesUrlTwentyOne="{{ asset('/images/Dev/BackEnd/Stack Overflow.png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/Dev/cyberSecurity/DarkReading.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/Dev/cyberSecurity/DanielMiessler.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/Dev/Mobile/medium.webp') }}"
    imgesUrlTwentyFive="{{ asset('/images/Dev/BackEnd/freeCodeCamp.png') }}"
    imgesUrlTwentySix="{{ asset('/images/Dev/cyberSecurity/NISTNVD.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/Dev/cyberSecurity/Intigriti.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/Dev/cyberSecurity/OpenBugBounty.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/Dev/cyberSecurity/KrebsonSecurity.avif') }}"
    imgesUrlThirty="{{ asset('/images/Dev/cyberSecurity/ExploitDatabase.png') }}"
    imgesUrlThirtyone="{{ asset('/images/Dev/cyberSecurity/RootMe.jpg') }}"
    imgesUrlThirtytwo="{{ asset('/images/Dev/cyberSecurity/OSINTFramework.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/Dev/cyberSecurity/Shodan.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/Dev/cyberSecurity/Censys.png') }}"
    imgesUrlThirtyfive="{{ asset('/images/Dev/cyberSecurity/AnyRun.png') }}"
    imgesUrlThirtysix="{{ asset('/images/Dev/cyberSecurity/HybridAnalysis.jpg') }}"
    imgesUrlThirtyseven="{{ asset('/images/Dev/cyberSecurity/VirusTotal.jpg') }}"
    routeNameOne="TryHackMe" routeNameTwo="MITREATTCK" routeNameThree="HackTheBox" routeNameFour="RoadmapSh" routeNameFive="PortSwiggerWebSecurityAcademy" routeNameSix="OverTheWire" routeNameSeven="picoCTF" routeNameEight="CTFtime" routeNameNine="HackerOne" routeNameTen="Bugcrowd" routeNameEleven="TheHackerNews" routeNameTowlve="CVEMitre"
    routeNameThirteen="BleepingComputer" routeNameFourteen="CyberDefenders" routeNameFifteen="LetsDefend" routeNameSixteen="VulnHub" routeNameSeventeen="OffSecLearningLibrary" routeNameEighteen="Cybrary" routeNameNineteen="OWASP" routeNametwenty="AntisyphonTraining" routeNametwentyone="StackOverflow" routeNametwentytwo="DarkReading" routeNametwentythree="DanielMiessler"
    routeNametwentyfour="medium" routeNametwentyfive="freeCodeCamp" routeNametwentysix="NISTNVD" routeNametwentyseven="Intigriti" routeNametwentyeight="OpenBugBounty" routeNametwentynine="KrebsonSecurity" routeNamethirty="ExploitDatabase" routeNamethirtyone="RootMe" routeNamethirtytwo="OSINTFramework" routeNamethirtythree="Shodan"
    routeNamethirtyfour="Censys" routeNamethirtyfive="AnyRun" routeNamethirtysix="HybridAnalysis" routeNamethirtyseven="VirusTotal">
</x-pages>
