<x-pages pageTitle="ChatAI"  title="ChatAI"
    imgesUrlOne="{{ asset('/images/AIROOM/ChatAI/ChatGPT.png') }}"
    imgesUrlTwo="{{ asset('/images/AIROOM/ChatAI/MetaAI.jpg') }}"
    imgesUrlThree="{{ asset('/images/AIROOM/ChatAI/Gemini.jpg') }}"
    imgesUrlFour="{{ asset('/images/AIROOM/ChatAI/Claude.jpg') }}"
    imgesUrlFive="{{ asset('/images/AIROOM/ChatAI/Copilot.png') }}"
    imgesUrlSix="{{ asset('/images/AIROOM/ChatAI/deepseek.jpg') }}"
    imgesUrlSeven="{{ asset('/images/AIROOM/ChatAI/munas.png') }}"
    imgesUrlEight="{{ asset('/images/AIROOM/ChatAI/Perplexity.png') }}"
    imgesUrlNine="{{ asset('/images/AIROOM/ChatAI/YouCom.jpg') }}"
    imgesUrlTen="{{ asset('/images/AIROOM/ChatAI/Phind.png') }}"
    imgesUrlEleven="{{ asset('/images/AIROOM/ChatAI/Poe.png') }}"
    imgesUrlTwelve="{{ asset('/images/Dev/AI/HuggingFace.png') }}"
    imgesUrlThirteen="{{ asset('/images/AIROOM/ChatAI/CharacterAI.png') }}"
    imgesUrlFourteen="{{ asset('/images/AIROOM/ChatAI/Replika.webp') }}"
    imgesUrlFifteen="{{ asset('/images/office/word/jasper.png') }}"
    imgesUrlSixteen="{{ asset('/images/office/word/Writesonic.jpg') }}"
    imgesUrlSeventeen="{{ asset('/images/AIROOM/ChatAI/Grok.webp') }}"
    imgesUrlEighteen="{{ asset('/images/AIROOM/ChatAI/PiAI.png') }}"
    imgesUrlNineteen="{{ asset('/images/AIROOM/ChatAI/Mistral.png') }}"
    imgesUrlTwenty="{{ asset('/images/AIROOM/ChatAI/Qwen.jpg') }}"
    imgesUrlTwentyOne="{{ asset('/images/AIROOM/ChatAI/Kimi.png') }}"
    imgesUrlTwentyTwo="{{ asset('/images/AIROOM/ChatAI/HIX.png') }}"
    imgesUrlTwentyThree="{{ asset('/images/AIROOM/ChatAI/Monica.png') }}"
    imgesUrlTwentyFour="{{ asset('/images/AIROOM/ChatAI/Blackbox.png') }}"
    imgesUrlTwentyFive="{{ asset('/images/AIROOM/ChatAI/Nova.png') }}"
    imgesUrlTwentySix="{{ asset('/images/AIROOM/ChatAI/AskAI.png') }}"
    imgesUrlTwentySeven="{{ asset('/images/AIROOM/ChatAI/GenieAI.png') }}"
    imgesUrlTwentyEight="{{ asset('/images/AIROOM/ChatAI/ChatOn.png') }}"
    imgesUrlTwentyNine="{{ asset('/images/AIROOM/ChatAI/Elicit.jpg') }}"
    imgesUrlThirty="{{ asset('/images/AIROOM/ChatAI/Consensus.png') }}"
    imgesUrlThirtyone="{{ asset('/images/AIROOM/ChatAI/SciSpace.png') }}"
    imgesUrlThirtytwo="{{ asset('/images/office/word/SemanticScholar.jpg') }}"
    imgesUrlThirtythree="{{ asset('/images/AIROOM/ChatAI/ResearchRabbit.png') }}"
    imgesUrlThirtyfour="{{ asset('/images/office/word/Rytr.jpg') }}"
    imgesUrlThirtyfive="{{ asset('/images/office/word/Anyword.jpg') }}"
    imgesUrlThirtysix="{{ asset('/images/AIROOM/ChatAI/NotionAI.png') }}"
    imgesUrlThirtyseven="{{ asset('/images/AIROOM/ChatAI/ClickUp.jpg') }}"
    routeNameOne="ChatGPT" routeNameTwo="MetaAI" routeNameThree="Gemini" routeNameFour="Claude" routeNameFive="Copilot" routeNameSix="deepseek" routeNameSeven="munas" routeNameEight="Perplexity" routeNameNine="YouCom" routeNameTen="Phind" routeNameEleven="Poe" routeNameTowlve="HuggingFace"
    routeNameThirteen="CharacterAI" routeNameFourteen="Replika" routeNameFifteen="jasper" routeNameSixteen="Writesonic" routeNameSeventeen="Grok" routeNameEighteen="PiAI" routeNameNineteen="Mistral" routeNametwenty="Qwen" routeNametwentyone="Kimi" routeNametwentytwo="HIX" routeNametwentythree="Monica"
    routeNametwentyfour="Blackbox" routeNametwentyfive="Nova" routeNametwentysix="AskAI" routeNametwentyseven="GenieAI" routeNametwentyeight="ChatOn" routeNametwentynine="Elicit" routeNamethirty="Consensus" routeNamethirtyone="SciSpace" routeNamethirtytwo="SemanticScholar" routeNamethirtythree="ResearchRabbit"
    routeNamethirtyfour="Rytr" routeNamethirtyfive="Anyword" routeNamethirtysix="NotionAI" routeNamethirtyseven="ClickUp">
</x-pages>
